#!/usr/bin/env python3
"""Regenerate CATALOG.md from catalog.json and check that the shelves and the
catalog agree: every PDF/epub under books/ and articles/ must have a record, and
every record must point at a file that exists. raw/ is unsorted and not checked.

    python3 catalog.py          # rewrite CATALOG.md, report mismatches, exit 1 on any
"""
import glob, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SHELVES = ("books", "articles")
EXTS = (".pdf", ".epub", ".djvu", ".txt", ".md", ".html")


def pages(path):
    try:
        import pypdf
        return len(pypdf.PdfReader(path).pages)
    except Exception:
        return None


def main():
    records = json.load(open(os.path.join(HERE, "catalog.json")))
    on_disk = set()
    for shelf in SHELVES:
        for p in glob.glob(os.path.join(HERE, shelf, "*")):
            if p.lower().endswith(EXTS):
                on_disk.add(os.path.relpath(p, HERE))
    listed = {r["file"] for r in records}
    bad = 0
    for f in sorted(on_disk - listed):
        print("NOT IN CATALOG:", f); bad += 1
    for f in sorted(listed - on_disk):
        print("MISSING FILE:  ", f); bad += 1

    def key(r):
        return (r["type"], r["author"].split(";")[0].split(" and ")[0].split()[-1].lower(), r.get("year") or 0)

    out = ["# Biblioteca", "",
           "A general library. Regenerated by `python3 catalog.py` from `catalog.json`; edit the",
           "JSON, not this file. Files live under `books/` and `articles/`; `raw/` holds scans and",
           "drops not yet cataloged.", ""]
    for shelf, label in (("book", "Books"), ("article", "Articles and chapters")):
        rows = [r for r in records if r["type"] == shelf]
        out += [f"## {label} ({len(rows)})", "",
                "| Author | Title | Year | Pages | Where published | Note |", "|---|---|---|---|---|---|"]
        for r in sorted(rows, key=key):
            n = pages(os.path.join(HERE, r["file"])) if os.path.exists(os.path.join(HERE, r["file"])) else None
            out.append("| {a} | [{t}]({f}) | {y} | {n} | {p} | {note} |".format(
                a=r["author"], t=r["title"].replace("|", "/"), f=r["file"], y=r.get("year", ""),
                n=n or "", p=r.get("publisher", "").replace("|", "/"), note=r.get("note", "").replace("|", "/")))
        out.append("")
    open(os.path.join(HERE, "CATALOG.md"), "w").write("\n".join(out))
    write_bib(records)
    print(f"CATALOG.md, references.bib, BIBLIOGRAPHY.md: {len(records)} records, {bad} mismatches")
    sys.exit(1 if bad else 0)


BIB_FIELDS = [("author", "bibauthor"), ("editor", "editor"), ("translator", "translator"), ("title", "title"),
              ("journal", "journal"), ("booktitle", "booktitle"), ("volume", "volume"), ("number", "number"),
              ("pages", "pages"), ("publisher", "bibpublisher"), ("address", "address"), ("year", "year"),
              ("doi", "doi"), ("language", "language"), ("note", "bibnote"), ("file", "file"),
              ("annote", "annotation")]


def bib_entry(r):
    """one BibTeX record; UTF-8 kept as is (use biblatex + biber, or bibtex8), titles brace-protected"""
    rr = dict(r)
    rr.setdefault("bibpublisher", r.get("publisher") if r.get("bibtype") in ("book", "incollection") else None)
    lines = [f"@{r.get('bibtype', 'misc')}{{{r['citekey']},"]
    for bib, src in BIB_FIELDS:
        v = rr.get(src)
        if v in (None, ""):
            continue
        v = str(v).replace("{", "").replace("}", "")
        if bib == "title":
            v = "{" + v + "}"
        lines.append(f"  {bib:<10} = {{{v}}},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("}")
    return "\n".join(lines)


def prose_names(s):
    """'Last, First and Last, First' -> 'First Last and First Last' for running text"""
    return " and ".join(" ".join(reversed([p.strip() for p in n.split(",", 1)])) if "," in n else n.strip()
                       for n in s.split(" and "))


def cite(r):
    """a Chicago-ish reference line for the human bibliography"""
    r = dict(r)
    for k in ("editor", "translator"):
        if r.get(k):
            r[k] = prose_names(r[k])
    a, t, y = r.get("bibauthor", r["author"]), r["title"], r.get("year", "n.d.")
    if r.get("bibtype") == "article":
        where = f"*{r['journal']}* {r.get('volume', '')}"
        if r.get("number"):
            where += f", no. {r['number']}"
        where += f" ({y})"
        if r.get("pages"):
            where += ": " + r["pages"].replace("--", "–")
        s = f"{a}. \"{t}.\" {where}."
        if r.get("doi"):
            s += f" https://doi.org/{r['doi']}."
        return s
    if r.get("bibtype") == "incollection":
        return (f"{a}. \"{t}.\" In *{r['booktitle']}*, edited by {r.get('editor', '')}. "
                f"{r.get('address', '')}: {r.get('publisher', '')}, {y}.")
    s = f"{a}. *{t}*."
    if r.get("editor"):
        s += f" Edited by {r['editor']}."
    if r.get("translator"):
        s += f" Translated by {r['translator']}."
    s += f" {r.get('address', '')}: {r.get('publisher', '')}, {y}."
    if r.get("bibnote"):
        s += f" {r['bibnote']}."
    return s.replace(" : ", " ")


def write_bib(records):
    recs = sorted(records, key=lambda r: r["citekey"])
    bib = ["% biblioteca: generated by catalog.py from catalog.json; edit the JSON, not this file.",
           "% UTF-8 throughout: compile with biblatex + biber (or bibtex8). `annote` carries the annotation.", ""]
    bib += [bib_entry(r) + "\n" for r in recs]
    open(os.path.join(HERE, "references.bib"), "w").write("\n".join(bib))
    md = ["# Biblioteca: annotated bibliography", "",
          "Generated by `python3 catalog.py` from `catalog.json` (edit the JSON, not this file); the same",
          "records as `references.bib`, whose `annote` field carries each annotation. Alphabetical by",
          "cite key.", ""]
    for r in recs:
        md += [f"**{r['citekey']}**  ", cite(r), "", r.get("annotation", r.get("note", "")), "",
               f"File: `{r['file']}`. Source: {r.get('source', '')}.", ""]
    open(os.path.join(HERE, "BIBLIOGRAPHY.md"), "w").write("\n".join(md))


if __name__ == "__main__":
    main()
