#!/usr/bin/env python3
"""Regenerate CATALOG.md from catalog.json and check that the shelves and the
catalog agree: every PDF/epub under books/ and articles/ must have a record, and
every record must point at a file that exists. raw/ is unsorted and not checked.

    python3 catalog.py          # rewrite CATALOG.md, report mismatches, exit 1 on any
"""
import glob, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SHELVES = ("books", "articles")
EXTS = (".pdf", ".epub", ".djvu", ".txt", ".md", ".html")


def pages(path):
    try:
        import pypdf
        return len(pypdf.PdfReader(path).pages)
    except Exception:
        return None


def main():
    records = json.load(open(os.path.join(HERE, "catalog.json")))
    on_disk = set()
    for shelf in SHELVES:
        for p in glob.glob(os.path.join(HERE, shelf, "*")):
            if p.lower().endswith(EXTS):
                on_disk.add(os.path.relpath(p, HERE))
    listed = {r["file"] for r in records}
    bad = 0
    for f in sorted(on_disk - listed):
        print("NOT IN CATALOG:", f); bad += 1
    for f in sorted(listed - on_disk):
        print("MISSING FILE:  ", f); bad += 1

    def key(r):
        return (r["type"], r["author"].split(";")[0].split(" and ")[0].split()[-1].lower(), r.get("year") or 0)

    out = ["# Biblioteca", "",
           "A general library. Regenerated by `python3 catalog.py` from `catalog.json`; edit the",
           "JSON, not this file. Files live under `books/` and `articles/`; `raw/` holds scans and",
           "drops not yet cataloged.", ""]
    for shelf, label in (("book", "Books"), ("article", "Articles and chapters")):
        rows = [r for r in records if r["type"] == shelf]
        out += [f"## {label} ({len(rows)})", "",
                "| Author | Title | Year | Pages | Where published | Note |", "|---|---|---|---|---|---|"]
        for r in sorted(rows, key=key):
            n = pages(os.path.join(HERE, r["file"])) if os.path.exists(os.path.join(HERE, r["file"])) else None
            out.append("| {a} | [{t}]({f}) | {y} | {n} | {p} | {note} |".format(
                a=r["author"], t=r["title"].replace("|", "/"), f=r["file"], y=r.get("year", ""),
                n=n or "", p=r.get("publisher", "").replace("|", "/"), note=r.get("note", "").replace("|", "/")))
        out.append("")
    open(os.path.join(HERE, "CATALOG.md"), "w").write("\n".join(out))
    print(f"CATALOG.md: {len(records)} records, {bad} mismatches")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
